version: "3.8"

services:
  app:
    depends_on:
      - postgres_db
    build: ./
    ports:
      - "${APP_PORT}:${APP_PORT}"
    volumes:
      - ./config.json:/config.json
    env_file:
      - .env
    environment:
      - APP_PORT=${APP_PORT}
    networks:
      - api_network
    restart: unless-stopped
  postgres_db:
    container_name: postgres_db
    image: postgres:latest
    volumes:
      - database:/var/lib/postgresql/data
    env_file:
      - .env
    ports:
      - "${POSTGRES_PORT}:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    networks:
      - api_network
    restart: always
volumes:
  database:
networks:
  api_network:
    driver: bridge
    name: api_network
